config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  
  authenticated :user do
    root "users#show", as: :user_root
    resources :users, only: [] do
      resources :items, only: [:create]  do
        put :complete
        put :archive
        put :activate
      end
    end
  end
  
  root to: "welcome#home"
end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :user
  
  validates :name, :user, presence: true
  before_save {self.state ||= :active }
  
  enum state: [:active, :completed, :archived]
  
  
  def activate
    self.state = :active
    self.activated_at = Date.today
    self.deactivated_at = nil
  end
  
  def deactivate(new_state)
    self.state = new_state
    self.deactivated_at = Date.today
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable
         
  validates :user_name, :email, presence: true
  validates :user_name, :email, uniqueness: true
  validates :email, length: { minimum: 3 }
  validates :user_name, length: { minimum: 1 }
  
  has_many :items
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
  
  
  protected
  
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:user_name] )
    devise_parameter_sanitizer.permit(:account_update, keys: [:user_name] ) 
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def create
    @user = current_user
    @item = @user.items.new(item_params)
    @item.user = current_user
    @item.activate
    @new_item = Item.new
    
    if @item.save
      flash.now[:notice] = "Task saved successfully"
    else
      flash[:error] = "Task failed to save"
    end
    
    respond_to do |format|
      format.html
      format.js
    end
  end
  
  def complete
    
    update_state(:completed)

    respond_to do |format|
      format.html
      format.js
    end
    
  end
  
  def archive
    
    update_state(:archived)
    
    respond_to do |format|
      format.html
      format.js
    end   
    
  end
  
  def activate
    update_state(:active)
    
    respond_to do |format|
      format.html
      format.js
    end
    
  end
  
  private
  
  def update_state(new_state)
    @item = Item.find(params[:item_id])
    
    if(new_state == :active)
      @item.activate
    else
      @item.deactivate(new_state)
    end
    
    if @item.save
      flash.now[:notice] = "#{@item.name} is now marked #{new_state.to_s}"
    else
      flash[:error] = "Task could not be marked #{new_state.to_s}"
    end
  end
  
  def item_params
    params.require(:item).permit(:name)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    if current_user
      @user = current_user
    else
      redirect_to new_user_session_path
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
  
  def inactive?(item)
    !(item.active?)
  end
  
  def time_to_archive(activated_at)
    distance_of_time_in_words(Date.today, activated_at + 7)
  end
  
  def time_to_delete(deactivated_at)
    distance_of_time_in_words(Date.today, deactivated_at + 30)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/items/_form.html.erb
<h4>Add a task</h4>
<%= form_for [user, item], remote: true do |f| %>
  <div class="form-group">
    <%= f.label :name, class: "sr-only" %>
    <div class="input-group">
      <span class="input-group-btn">
      <%= button_tag(class: 'btn btn-primary') do %>
        <i class="glyphicon glyphicon-plus"></i>
      <% end %>
      </span>
      <%= f.text_field :name, class: "form-control", placeholder: "Enter a new task" %>
    </div>
    
  </div>

<% end %>

app/views/items/_item.html.erb
<%= content_tag :div, class: "media", id: "task-#{item.id}" do %>
  <div class="media-body">
    <div class="btn-group pull-left" role="group">
      <% if inactive?(item) %>
        <%= link_to "", user_item_activate_path(current_user, item), class: 'glyphicon glyphicon-repeat', title: "Re-activate Task", method: :put, remote: true %> 
      <% else %>
        <%= link_to "", user_item_complete_path(current_user, item), class: 'glyphicon glyphicon-ok', title: "Complete Task", method: :put, remote: true %> |
        <%= link_to "", user_item_archive_path(current_user, item), class: 'glyphicon glyphicon-remove', title: "Remove Task", method: :put, remote: true %>
      <% end %>
    </div>
    <p><%= item.name %></p>
    <small class="pull-right">
      <% if inactive?(item) %>
        <%= "Will be deleted in #{time_to_delete(item.deactivated_at)}" %>
      <% else %>
        <%= "Will be archived in #{time_to_archive(item.activated_at)}" %>
      <% end %>
    </small>
  </div>
<% end %>

app/views/items/activate.js.erb
<% if @item.valid? %>
  $('#task-<%= @item.id %>').delay(1000).slideUp('slow');
  $('.js-active-tasks').append("<%= escape_javascript(render(@item)) %>");
  $('.flash').prepend("<div class='alert alert-success'><button type='button' class='close' data-dismiss='alert'>&times;</button><%= flash[:notice] %></div>");
<% else %>
  $('.flash').prepend("<div class='alert alert-danger'><button type='button' class='close' data-dismiss='alert'>&times;</button><%= flash[:error] %></div>");
<% end %>
$('.alert').delay(5000).fadeOut();

app/views/items/archive.js.erb
<% if @item.valid? %>
  $('#task-<%= @item.id %>').addClass("bg-warning");
  $('#task-<%= @item.id %> p').wrap("<strike>");
  $('#task-<%= @item.id %>').delay(1000).slideUp('slow', function() {
    $('#task-<%= @item.id %>').remove();
  });
  $('.js-archived-tasks').append("<%= escape_javascript(render(@item)) %>");
  $('.flash').prepend("<div class='alert alert-success'><button type='button' class='close' data-dismiss='alert'>&times;</button><%= flash[:notice] %></div>");
<% else %>
  $('.flash').prepend("<div class='alert alert-danger'><button type='button' class='close' data-dismiss='alert'>&times;</button><%= flash[:error] %></div>");
<% end %>
$('.alert').delay(5000).fadeOut();

app/views/items/complete.js.erb
<% if @item.valid? %>
  $('#task-<%= @item.id %>').addClass("bg-success");
  $('#task-<%= @item.id %> p').wrap("<strike>");
  $('#task-<%= @item.id %>').delay(1000).slideUp('slow', function() {
    $('#task-<%= @item.id %>').remove();
  });
  $('.js-completed-tasks').append("<%= escape_javascript(render(@item)) %>");
  $('.flash').prepend("<div class='alert alert-success'><button type='button' class='close' data-dismiss='alert'>&times;</button><%= flash[:notice] %></div>");
<% else %>
  $('.flash').prepend("<div class='alert alert-danger'><button type='button' class='close' data-dismiss='alert'>&times;</button><%= flash[:error] %></div>");
<% end %>
$('.alert').delay(5000).fadeOut();

app/views/items/create.js.erb
<% if @item.valid? %>
  $('.js-active-tasks').append("<%= escape_javascript(render(@item)) %>");
  $('.flash').prepend("<div class='alert alert-success'><button type='button' class='close' data-dismiss='alert'>&times;</button><%= flash[:notice] %></div>");
  $('.new-task').html("<%= escape_javascript(render 'items/form', item: @new_item, user: @user) %>");
<% else %>
  $('.flash').prepend("<div class='alert alert-danger'><button type='button' class='close' data-dismiss='alert'>&times;</button><%= flash[:error] %></div>");
  $('.new-task').html("<%= escape_javascript(render 'items/form', item: @item, user: @user) %>");
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blocitoff</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <div class="container">
      <ul class="nav nav-tabs">
        <div class="pull-right">
          <% if user_signed_in? %>
            Signed in as: <strong><%= current_user.user_name %></strong> |
            <%= link_to 'Edit profile', edit_user_registration_path, class: 'navbar-link' %> - <%= link_to "Sign out", destroy_user_session_path, method: :delete, class: 'navbar-link' %>
          <% else %>
            <%= link_to "Sign Up", new_user_registration_path, class: 'navbar-link' %> -
            <%= link_to "Sign In", new_user_session_path, class: 'navbar-link'  %>
          <% end %>
        </div>
      </ul>
      <div class="flash">
        <% if flash[:notice] %>
          <div class="alert alert-success">
            <button type="button" class="close" data-dismiss="alert">&times;</button>
            <%= flash[:notice] %>
          </div>
        <% elsif flash[:error] %>
          <div class="alert alert-danger">
            <button type="button" class="close" data-dismiss="alert">&times;</button>
            <%= flash[:error] %>
          </div>
        <% elsif flash[:alert] %>
          <div class="alert alert-warning">
            <button type="button" class="close" data-dismiss="alert">&times;</button>
            <%= flash[:alert] %>
          </div>
        <% end %>
      </div>
      <%= yield %>
    </div>
  </body>
</html>

app/views/users/show.html.erb
<div>
  <h1>
    <%= "#{@user.user_name}'s to do list" %> 
  </h1>
</div>

<div class="row">
  <div class="col-md-8">

    <ul class="nav nav-tabs" id="task-tabs">
      <li class="active"><a href="#active-tasks" data-target="#active-tasks" data-toggle="tab">Active Tasks</a></li>
      <li><a href="#completed-tasks" data-target="#completed-tasks" data-toggle="tab">Completed Tasks</a></li>
      <li><a href="#archived-tasks" data-target="#archived-tasks" data-toggle="tab">Archived Tasks</a></li>
    </ul>
    <div class="tab-content">
      <div class="tab-pane active" id="active-tasks">
        <div class="new-task">
          <%= render 'items/form', item: Item.new, user: @user %>
        </div>
        <div class="js-active-tasks">
          <%= render @user.items.active %>
        </div>

      </div>
      
      <div class="tab-pane" id="completed-tasks">
        <div class="js-completed-tasks">
          <%= render @user.items.completed %>
        </div>
      </div>
      
      <div class="tab-pane" id="archived-tasks">
        <div class="js-archived-tasks">
          <%= render @user.items.archived %>
        </div>
      </div>      
    </div>


  </div>
</div>

app/views/welcome/home.html.erb
<br>
<div class="jumbotron">
  <h1>Blocitoff:</h1>
  <p>A self-destructing to-do list to keep you focused on the things that really matter.</p>
</div>